#ifndef AERON_PYTHON_CONFIGURATION_H
#define AERON_PYTHON_CONFIGURATION_H

#define DEFAULT_CHANNEL "aeron:udp?endpoint=localhost:20121"
#define DEFAULT_STREAM_ID (1001)
#define DEFAULT_FRAGMENT_COUNT_LIMIT (10)

#endif //AERON_PYTHON_CONFIGURATION_H
