# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Aeron
        run: |
          git clone --branch 1.38.2 --depth 1 https://github.com/real-logic/aeron.git
          mkdir --parents aeron/cppbuild/Debug
          cd aeron/cppbuild/Debug
          cmake -DCMAKE_BUILD_TYPE=Debug ../..
          cmake --build . --clean-first
          cmake --install .
      - name: Upgrade pip
        run: |
          pip install --upgrade pip
      - name: Build package
        run: |
          pip install .
